### PR TITLE
Fix zlib packages for Fedora 40+

### LINKED ISSUE #5478: Fedora 40+: `zlib` and `zlib-devel` packages no longer exist
In Fedora 40+, `zlib` and `zlib-devel` no longer exist. Instead, the packages to install are now [`zlib-ng-compat`](https://packages.fedoraproject.org/pkgs/zlib-ng/zlib-ng-compat/) and [`zlib-ng-compat-devel`](https://packages.fedoraproject.org/pkgs/zlib-ng/zlib-ng-compat-devel/).

Ruby 3.3.3 compiles fine with those packages...

### PR DESCRIPTION
**Pull request by denschub**
I did not touch `yum` for Fedora, because that is shared with CentOS (which is dead and I can't test), and newer Fedora versions default to `dnf` anyway.

Fixes #5478.

### CODE REVIEW

**Review by pkuczynski — APPROVED** [review]

**Review by pkuczynski — DISMISSED** [review]

**Comment by pkuczynski** [comment]
Great! Thanks!

**Review by pkuczynski — APPROVED** [review]

**Comment by pkuczynski** [comment]
@denschub maybe you would also like to look at some other Fedora issues? https://github.com/rvm/rvm/issues?q=is%3Aissue+is%3Aopen+label%3A%22platform%3A+fedora%22

**Comment by denschub** [comment]
@pkuczynski I just sent you an email as a reply to your org invite. :) As much as I'd love to, I can't commit the time. I submitted those two PRs because the issues were blocking our installation guides and I wanted to make sure there's a fix, but I'm not really working with Ruby anymore, I'm not going to start new Ruby projects, and I have way too much on my plate already. Sorry.

**Comment by pkuczynski** [comment]
Sure! Thank you for your contribution nonetheless :)

**Pull request merged**
