### PR TITLE
Remove unused duplicate rvm-test/ directory

### PR DESCRIPTION
**Pull request by eregon**
* Tests are in tests/ since #5106.

### CODE REVIEW

**Review by pkuczynski — APPROVED** [review]

**Comment by pkuczynski** [comment]
You wont be able to merge until you add CHANGELOG entry... I can force it if you want...

**Comment by eregon** [comment]
Yeah, does it make sense to add a CHANGELOG entry for this?
It's not really a feature, bug, new version or documentation.

**Comment by eregon** [comment]
Since it's not a user-facing change, I think a CHANGELOG entry makes little sense, so yeah I think forcing it or fuinding another way to satisfy Mergeable would be good.

**Comment by pkuczynski** [comment]
Yeah, does not make sense, hence I offered to force it

**Comment by eregon** [comment]
@pkuczynski  Could you force merge it?

**Pull request merged**
