### PR TITLE
SSE2-CPU required for compiling Ruby 2.1.1 with rvm?

### PR DESCRIPTION
**Pull request by mpapis**
Hi,
I have the following problem with installing Ruby 2.1.1:
when I call `rvm install 2.1.1` on a Debian testing/jessie machine that has an Athlon XP 2600+ processor (no SSE2-support), the compiling process is aborted after a few minutes with the following output:

``` bash
carsten@debbie ~ % rvm install 2.1.1
ruby-2.1.1 - #removing src/ruby-2.1.1 - please wait
Searching for binary rubies, this might take some time.
No binary rubies available for: debian/jessie_sid/i386/ruby-2.1.1.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for debian.
Requirements installation successful.
Installing Ruby from source to: /home/carsten/.rvm/rubies/ruby-2.1.1, this may take a while depending on your cpu(s)...
ruby-2.1.1 - #downloading ruby-2.1.1, this may take a while depending on your connection...
ruby-2.1.1 - #extracting ruby-2.1.1 to /home/carsten/.rvm/src/ruby-2.1.1 - please wait
ruby-2.1.1 - #applying patch /home/carsten/.rvm/patches/ruby/changeset_r45225.diff - please wait
ruby-2.1.1 - #applying patch /home/carsten/.rvm/patches/ruby/changeset_r45240.diff - please wait
ruby-2.1.1 - #configuring - please wait
ruby-2.1.1 - #post-configuration - please wait
ruby-2.1.1 - #compiling - please wait
Error running '__rvm_make -j1',
showing last 15 lines of /home/carsten/.rvm/log/1399922963_ruby-2.1.1/make.log
compiling ./enc/ascii.c
compiling ./enc/us_ascii.c
compiling ./enc/unicode.c
compiling ./enc/utf_8.c
compiling newline.c
compiling ./missing/strlcpy.c
compiling ./missing/strlcat.c
compiling ./missing/setproctitle.c
compiling addr2line.c
compiling dmyext.c
linking miniruby
uncommon.mk:543: recipe for target '.rbconfig.time' failed
make: *** [.rbconfig.time] Ungültiger Maschinenbefehl (Speicherauszug erstellt)
  257,40s user 9,16s system 53% cpu 8:21,28 total
+__rvm_make:0:cmdor> return 2
There has been an error while running make. Halting the installation.
```

'Ungültiger Maschinenbefehl (Speicherauszug erstellt)' would be 'Illegal instruction (core dumped)' in English.

Performing the same operation on an Intel Pentium 4 M (SSE2-support) with the same Linux distribution completes without errors. I'm using rvm 1.25.25 (stable) by the way.

Is it possible to work around this issue somehow? I hope I don't have to get a new computer to keep up with current Ruby development...

Regards,
Carsten

### CODE REVIEW

**Comment by samsoft00** [comment]
I've been facing difficulties setting rvm up for my environment on window 8.1 after running the below command, 
```
rvm autolib disable
rvm install 1.9
```
received the error below, 
```
...
Error running '__rvm_make -j4',
showing last 15 lines of /cygdrive/c/Users/Al-Mukhtarr/.rvm/log/1432932501_ruby-
1.9.3-p551/make.log
...
jango/bin:/cygdrive/c/Users/Al-Mukhtarr/.rvm/bin
command(2): __rvm_make -j4
++ make -j4
bash: make: command not found
++ return 127
There has been an error while running make. Halting the installation.
```
but when i check the .rvm folder, the ruby 1.9 was successfully download but sad, when i run 
```
rvm use 1.9
split out ==>  

$ rvm use 1.9
ruby-1.9.3-p551 is not installed.
To install do: 'rvm install ruby-1.9.3-p551'
```

Please help!

**Comment by mpapis** [comment]
@samsoft00 this happens because you did `rvm autolib disable` - to restore proper RVM behaviour run: `rvm autolib enable` and try installing ruby again: `rvm install 1.9`

**Comment by samsoft00** [comment]
@mpapis Thanks for your quick response... after trying your suggestion, here are the display information 

```
$ rvm install 1.9
Searching for binary rubies, this might take some time.
No binary rubies available for: cygwin/unknown/x86_64/ruby-1.9.3-p551.
Continuing with compilation. Please read 'rvm help mount' to get more informatio
n on binary rubies.
Checking requirements for cygwin.
Installing requirements for cygwin.
Updating system.
Installing required packages: patch, openssl-devel, libyaml-devel, libtool, biso
n, patch, cygwin32-readline..
Error running 'requirements_cygwin_libs_install patch openssl-devel libyaml-deve
l libtool bison patch cygwin32-readline',
showing last 15 lines of /cygdrive/c/Users/Al-Mukhtarr/.rvm/log/1432936626_ruby-
1.9.3-p551/package_install_patch_openssl-devel_libyaml-devel_libtool_bison_patch
_cygwin32-readline.log
    ${__manager} -q -P "${__packages_list// /,}" || return $?
}
current path: /cygdrive/c/Users/Al-Mukhtarr
PATH=/usr/local/bin:/usr/bin:/cygdrive/c/Program Files/ImageMagick-6.9.1-Q16:/cy
gdrive/c/Program Files (x86)/iis express/PHP/v5.6:/cygdrive/c/Program Files/Imag
eMagick-6.8.9-Q16:/cygdrive/c/Windows/system32:/cygdrive/c/Windows:/cygdrive/c/W
indows/System32/Wbem:/cygdrive/c/Windows/System32/WindowsPowerShell/v1.0:/cygdri
ve/c/Program Files/Microsoft/Web Platform Installer:/cygdrive/c/Program Files (x
86)/Microsoft ASP.NET/ASP.NET Web Pages/v1.0:/cygdrive/c/Program Files (x86)/Win
dows Kits/8.0/Windows Performance Toolkit:/cygdrive/c/Program Files/Microsoft SQ
L Server/110/Tools/Binn:/cygdrive/c/Program Files (x86)/Intel/OpenCL SDK/2.0/bin
/x86:/cygdrive/c/Program Files (x86)/Intel/OpenCL SDK/2.0/bin/x64:/cygdrive/c/Re
search In Motion/BlackBerry 10 WebWorks SDK 1.0.4.11/dependencies/tools:/cygdriv
e/c/Program Files/Intel/WiFi/bin:/cygdrive/c/Program Files/Common Files/Intel/Wi
relessCommon:/cygdrive/c/apache-maven-3.1.1/bin:/cygdrive/c/Program Files (x86)/
Nimrod/bin:/cygdrive/c/Program Files (x86)/Nimrod/dist/mingw/bin:/cygdrive/c/Pro
gram Files (x86)/Nimrod/dist:/cygdrive/c/Program Files (x86)/Microsoft SQL Serve
r/100/Tools/Binn:/cygdrive/c/Program Files/Microsoft SQL Server/100/Tools/Binn:/
cygdrive/c/Program Files/Microsoft SQL Server/100/DTS/Binn:/cygdrive/c/Program F
iles (x86)/Microso:/cygdrive/c/ProgramData/ComposerSetup/bin:/cygdrive/c/Program
 Files (x86)/Bitvise SSH Client:/cygdrive/c/Program Files (x86)/Skype/Phone:/cyg
drive/c/Program Files (x86)/Git/cmd:/cygdrive/c/Ruby187/bin:/cygdrive/c/Program
Files/Android/android-sdk/platform-tools:/cygdrive/c/adt-bundle-windows-x86_64-2
0130219/sdk/tools:/cygdrive/c/apache-ant-1.9.2/bin:/cygdrive/c/Users/Al-Mukhtarr
/AppData/Roaming/npm:/cygdrive/c/Program Files/BlackBerry/BB10 WebWorks SDK 2.1.
0.13:/cygdrive/c/Program Files/BlackBerry/BB10 WebWorks SDK 2.1.0.13/cordova-bla
ckberry/bin/dependencies/bb-tools/bin:/cygdrive/c/Python27:/cygdrive/c/Python27/
python.exe:/cygdrive/c/Python27/Scripts:/cygdrive/c/Python27/Lib/site-packages/d
jango/bin:/cygdrive/c/Users/Al-Mukhtarr/.rvm/bin
command(8): requirements_cygwin_libs_install patch openssl-devel libyaml-devel l
ibtool bison patch cygwin32-readline
++ typeset __packages_list __manager
++ [[ x86_64 == \x\8\6\_\6\4 ]]
++ __manager=setup-x86_64.exe
++ rvm_debug '__manager: setup-x86_64.exe'
++ ((  0  ))
++ return 0
++ __packages_list='patch openssl-devel libyaml-devel libtool bison patch cygwin
32-readline'
++ setup-x86_64.exe -q -P patch,openssl-devel,libyaml-devel,libtool,bison,patch,
cygwin32-readline
bash: setup-x86_64.exe: command not found
++ return 127
Requirements installation failed with status: 127.
```

**Comment by mpapis** [comment]
@samsoft00 this is different issue, please open a new ticket

**Comment by samsoft00** [comment]
after work around and following the instruction here... https://github.com/rvm/rvm/issues/2736#issuecomment-38551623 i got this. 

```
...
ruby-2.2.2 - #compiling.................................................
Error running '__rvm_make -j4',
showing last 15 lines of /cygdrive/c/Users/Al-Mukhtarr/.rvm/log/1432937907_ruby-
2.2.2/make.log
exts.mk:118: recipe for target 'ext/-test-/printf/all' failed
make[1]: *** [ext/-test-/printf/all] Error 2
make[1]: *** Waiting for unfinished jobs....
compiling receiver.c
linking shared-object -test-/rational.so
linking shared-object -test-/recursion.so
compiling super.c
linking shared-object -test-/proc.so
make[2]: Leaving directory '/cygdrive/c/Users/Al-Mukhtarr/.rvm/src/ruby-2.2.2/ex
t/-test-/recursion'
make[2]: Leaving directory '/cygdrive/c/Users/Al-Mukhtarr/.rvm/src/ruby-2.2.2/ex
t/-test-/rational'
make[2]: Leaving directory '/cygdrive/c/Users/Al-Mukhtarr/.rvm/src/ruby-2.2.2/ex
t/-test-/proc'
make[1]: Leaving directory '/cygdrive/c/Users/Al-Mukhtarr/.rvm/src/ruby-2.2.2'
uncommon.mk:189: recipe for target 'build-ext' failed
make: *** [build-ext] Error 2
++ return 2
There has been an error while running make. Halting the installation.
```
Please how do i resolve this error... thanks

**Comment by mpapis** [comment]
@samsoft00 please open a new ticket and include all the things you had to do manually to get there

**Comment by shell-permission** [comment]
can u help me ?

`root@kali:~# rvm install 2.3.3
Searching for binary rubies, this might take some time.
No binary rubies available for: debian/Kali_Linux_Rolling/x86_64/ruby-2.3.3.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for debian.
Installing requirements for debian.
Updating system.
Installing required packages: libreadline6-dev..
Requirements installation successful.
Installing Ruby from source to: /usr/local/rvm/rubies/ruby-2.3.3, this may take a while depending on your cpu(s)...
ruby-2.3.3 - #downloading ruby-2.3.3, this may take a while depending on your connection...
######################################################################## 100.0%
ruby-2.3.3 - #extracting ruby-2.3.3 to /usr/local/rvm/src/ruby-2.3.3....
ruby-2.3.3 - #configuring..........................................................
ruby-2.3.3 - #post-configuration..
ruby-2.3.3 - #compiling..........................................................................
Error running '__rvm_make -j2',
showing last 15 lines of /usr/local/rvm/log/1482942641_ruby-2.3.3/make.log
     memset(ctx, 0, sizeof(HMAC_CTX));
                           ^~~~~~~~
Makefile:301: recipe for target 'openssl_missing.o' failed
make[2]: *** [openssl_missing.o] Error 1
make[2]: Leaving directory '/usr/local/rvm/src/ruby-2.3.3/ext/openssl'
exts.mk:210: recipe for target 'ext/openssl/all' failed
make[1]: *** [ext/openssl/all] Error 2
make[1]: *** Waiting for unfinished jobs....
installing default nkf libraries
linking shared-object nkf.so
make[2]: Leaving directory '/usr/local/rvm/src/ruby-2.3.3/ext/nkf'
make[1]: Leaving directory '/usr/local/rvm/src/ruby-2.3.3'
uncommon.mk:203: recipe for target 'build-ext' failed
make: *** [build-ext] Error 2
++ return 2
There has been an error while running make. Halting the installation.
`

**Comment by shell-permission** [comment]
root@kali:~# rvm info system
```
  system:
    uname:       "Linux kali 4.6.0-kali1-amd64 #1 SMP Debian 4.6.4-1kali1 (2016-07-21) x86_64 GNU/Linux"
    system:      "debian/Kali_Linux_Rolling/x86_64"
    bash:        "/bin/bash => GNU bash, version 4.3.46(1)-release (x86_64-pc-linux-gnu)"
    zsh:         "/usr/bin/zsh => zsh 5.2 (x86_64-debian-linux-gnu)"
```

root@kali:~# cat /proc/cpuinfo
```
processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 22
model		: 48
model name	: AMD A8-6410 APU with AMD Radeon R5 Graphics
stepping	: 1
microcode	: 0x6000626
cpu MHz		: 1996.275
cache size	: 2048 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 2
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt rdtscp lm rep_good nopl extd_apicid eagerfpu pni pclmulqdq ssse3 cx16 sse4_1 sse4_2 movbe popcnt aes rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch vmmcall arat
bugs		: fxsave_leak sysret_ss_attrs
bogomips	: 3992.55
TLB size	: 1024 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: AuthenticAMD
cpu family	: 22
model		: 48
model name	: AMD A8-6410 APU with AMD Radeon R5 Graphics
stepping	: 1
microcode	: 0x6000626
cpu MHz		: 1996.275
cache size	: 2048 KB
physical id	: 0
siblings	: 2
core id		: 1
cpu cores	: 2
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt rdtscp lm rep_good nopl extd_apicid eagerfpu pni pclmulqdq ssse3 cx16 sse4_1 sse4_2 movbe popcnt aes rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch vmmcall arat
bugs		: fxsave_leak sysret_ss_attrs
bogomips	: 3992.55
TLB size	: 1024 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:
```

**Comment by mpapis** [comment]
@shell-permission please open a new ticket with all the details

**Pull request merged**
