### PR TITLE
UPDATE signals handling

### LINKED ISSUE #4422: Unable to pass SIGINT signal (control-C) on 1.29.4
## Description

After installing 1.29.4, when I log in to a bash shell, (and it runs the rvmrc), I cannot press control-C to have it clear the current line of shell code. It appears that signals are being trapped, and not making it to bash.

On 1.29.3, this was working.
I installed rvm from https://github.com/Wasapl/rvm/commit/22945f8abfb2cf01354d12d977c7f9ad60e15d32 (which is really just the same as 1.29.4, without https://github.com/rvm/rvm/pull/4417), and the behavior started working again.

(I used `rvm get branch add-default-gem-bundler --source github.com/Wasapl/rvm` to install this branch)

## Steps to reproduce

- When we log into our AWS linux boxes, it doesn't work.
- Strangely, on our mac os x developer laptops, it still works fine. (I don't know why)

## Expected behavior

- pressing control-c should clear the current command
- when running a `tail -f <file>`, pressing control-C should stop the tail

## Actual behavior

- the shell is not cleared,
- the tail is not stopped

## Environment info

```
$ rvm info

ruby-2.5.1:

  system:
    uname:        "Linux <redacted> 4.14.33-51.34.amzn1.x86_64 #1 SMP Fri Apr 13 18:18:26 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux"
    name:         "Amazon"
    version:      "2017.09"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)"
    zsh:          " => not installed"
    remote_path:  "amazon/2017.09/x86_64"

  rvm:
    version:      "1.29.4 (latest)"
    updated:      "3 days 8 hours 15 minutes 14 seconds ago"
    path:         "/home/badges/.rvm"
    autolibs:     "[disable] Limit RVM automation as much as possible."

  ruby:
    interpreter:  "ruby"
    version:      "2.5.1p57"
    date:         "2018-03-29"
    platform:     "x86_64-linux"
    patchlevel:   "2018-03-29 revision 63029"
    full_version: "ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]"

  homes:
    gem:          "/home/badges/.rvm/gems/ruby-2.5.1"
    ruby:         "/home/badges/.rvm/rubies/ruby-2.5.1"

  binaries:
    ruby:         "/home/badges/.rvm/rubies/ruby-2.5.1/bin/ruby"
    irb:          "/home/badges/.rvm/rubies/ruby-2.5.1/bin/irb"
    gem:          "/home/badges/.rvm/rubies/ruby-2.5.1/bin/gem"
    rake:         "/home/badges/.rvm/gems/ruby-2.5.1@global/bin/rake"

  environment:
    PATH:         "/home/badges/.rvm/gems/ruby-2.5.1/bin:/home/badges/.rvm/gems/ruby-2.5.1@global/bin:/home/badges/.rvm/rubies/ruby-2.5.1/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/aws/bin:/home/badges/.rvm/bin:/home/badges/.local/bin:/home/badges/bin"
    GEM_HOME:     "/home/badges/.rvm/gems/ruby-2.5.1"
    GEM_PATH:     "/home/badges/.rvm/gems/ruby-2.5.1:/home/badges/.rvm/gems/ruby-2.5.1@global"
    MY_RUBY_HOME: "/home/badges/.rvm/rubies/ruby-2.5.1"
    IRBRC:        "/home/badges/.rvm/rubies/ruby-2.5.1/.irbrc"
    RUBYOPT:      ""
    gemset:       ""
```

Note, my local (working) install is:
```
 rvm info

ruby-2.3.7@push:

  system:
    uname:        "Darwin Robins-MacBook-Pro.local 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64"
    name:         "OSX"
    version:      "10.13"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)"
    zsh:          "/bin/zsh => zsh 5.3 (x86_64-apple-darwin17.0)"
    remote_path:  "osx/10.13/x86_64"

  rvm:
    version:      "1.29.4 (latest)"
    updated:      "2 minutes 54 seconds ago"
    path:         "/Users/robindunlop/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "ruby"
    version:      "2.3.7p456"
    date:         "2018-03-28"
    platform:     "x86_64-darwin17"
    patchlevel:   "2018-03-28 revision 63024"
    full_version: "ruby 2.3.7p456 (2018-03-28 revision 63024) [x86_64-darwin17]"

  homes:
    gem:          "/Users/robindunlop/.rvm/gems/ruby-2.3.7@push"
    ruby:         "/Users/robindunlop/.rvm/rubies/ruby-2.3.7"

  binaries:
    ruby:         "/Users/robindunlop/.rvm/rubies/ruby-2.3.7/bin/ruby"
    irb:          "/Users/robindunlop/.rvm/rubies/ruby-2.3.7/bin/irb"
    gem:          "/Users/robindunlop/.rvm/rubies/ruby-2.3.7/bin/gem"
    rake:         "/Users/robindunlop/.rvm/gems/ruby-2.3.7@push/bin/rake"

  environment:
    PATH:         "/Users/robindunlop/.rvm/gems/ruby-2.3.7@push/bin:/Users/robindunlop/.rvm/gems/ruby-2.3.7@global/bin:/Users/robindunlop/.rvm/rubies/ruby-2.3.7/bin:/Users/robindunlop/.rvm/bin:/usr/local/heroku/bin:/Users/robindunlop/.bin:.git/safe/../../bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/MacGPG2/bin:/opt/X11/bin"
    GEM_HOME:     "/Users/robindunlop/.rvm/gems/ruby-2.3.7@push"
    GEM_PATH:     "/Users/robindunlop/.rvm/gems/ruby-2.3.7@push:/Users/robindunlop/.rvm/gems/ruby-2.3.7@global"
    MY_RUBY_HOME: "/Users/robindunlop/.rvm/rubies/ruby-2.3.7"
    IRBRC:        "/Users/robindunlop/.rvm/rubies/ruby-2.3.7/.irbrc"
    RUBYOPT:      ""
    gemset:       "push"
```

### PR DESCRIPTION
**Pull request by phoolish**
Fixes #4422 on Amazon Linux 2018.03

Per @charlietag comment at https://github.com/rvm/rvm/commit/3d9b93b3ce1a0651c3c7cc23193957f619f65fd9#r29693653:

> Please try modify this line as following:
> ````
> trap >/dev/null
> _rvm_old_traps=$( trap | __rvm_grep -E 'EXIT|HUP|INT|QUIT|TERM' )
> trap >/dev/null
> ````
> Otherwise (trap) will always get the following result:
> trap -- '' SIGINT
> trap -- '' SIGQUIT
> This means.... INT QUIT (__rvm_grep) will always be trapped.
> This means... My ctrl+c will always be blocked....

### CODE REVIEW

**Comment by charlietag** [comment]
@Wasapl  This is how I tried.  I'm still trying to figure out why...

- My test code

<pre>
# cat test.sh 
#!/bin/bash
trap

echo "-------------- TEST 1 ----------------------"
trap >/dev/null
OLD_TRAP="$(grep -E 'EXIT|HUP|INT|QUIT|TERM' <(trap) )"
echo "${OLD_TRAP}"

echo "--------------- TEST 2 ---------------------"
OLD_TRAP="$(grep -E 'EXIT|HUP|INT|QUIT|TERM' <(trap) )"
echo "${OLD_TRAP}"

echo "---------------- TEST 3 --------------------"
OLD_TRAP="$(trap |grep -E 'EXIT|HUP|INT|QUIT|TERM' )"
echo "${OLD_TRAP}"

echo "---------------- TEST 4 --------------------"
trap >/dev/null
OLD_TRAP="$(trap |grep -E 'EXIT|HUP|INT|QUIT|TERM' )"
echo "${OLD_TRAP}"
</pre>

- Result

<pre>
# ./test.sh
-------------- TEST 1 ----------------------
trap -- '' SIGINT
trap -- '' SIGQUIT
--------------- TEST 2 ---------------------
trap -- '' SIGINT
trap -- '' SIGQUIT
---------------- TEST 3 --------------------

---------------- TEST 4 --------------------
</pre>

**Comment by charlietag** [comment]
<pre>
# lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.4.1708 (Core) 
Release:        7.4.1708
Codename:       Core
</pre>

**Comment by Wasapl** [comment]
@charlietag you have to restore traps between different test, otherwise first tests will influence second ones.
Can you please test your fix of `environment` script without `trap >/dev/null` commands. I believe it will work.

**Comment by charlietag** [comment]
@Wasapl 
You're right !! It works without `trap > /dev/null`
I thought I have to type in `trap` first to enable trap. 
I was wrong.

So just
<pre>
_rvm_old_traps=$( trap | __rvm_grep -E 'EXIT|HUP|INT|QUIT|TERM' )`
</pre>
is OK on my CentOS 7. Thanks for your explanation .

And I was wondering what's difference between `trap` and `(trap)`.
And I found that.
By default trap list in shell should be empty.  But using trap this way cat <(trap),  it's not ! I think CentOS is doing something for this `cat` usage.

- Test

<pre>
#!/bin/bash
echo "-------------- TEST 1 ----------------------"
OLD_TRAP="$(cat <(trap) )"
echo "${OLD_TRAP}"

echo "--------------- TEST 2 ---------------------"
OLD_TRAP="$(trap)"
echo "${OLD_TRAP}"
</pre>

- Result

<pre>
-------------- TEST 1 ----------------------
trap -- '' SIGINT
trap -- '' SIGQUIT
--------------- TEST 2 ---------------------

</pre>

**Comment by Wasapl** [comment]
@charlietag, In that case, please change this PR accordingly and I'll approve it :))

**Comment by phoolish** [comment]
@Wasapl updated

**Comment by Wasapl** [comment]
@mpapis can you please review and merge this PR ?

**Comment by mpapis** [comment]
merged in 6bc22a4155f5b865e45a7c9b021000b0bebf1dae

**Pull request closed without merging**
