### PR TITLE
Fix Termux

### LINKED ISSUE #5003: Termux: The package list of dependencies is out of date
## Description

Termux does no longer ship `-dev` packages. 
See their [FAQ](https://wiki.termux.com/wiki/FAQ):
> Where are all the *-dev packages?
>In Termux they are not needed because development files are not split from the main package. Now, for example instead of libxml2-dev you will need just libxml2. 

## Steps to reproduce

 1. Install Termux
 2. Run the RVM install script
 3. Try to install anything with rvm

## Expected behavior

I'd expect this to fetch the right deps and start building ruby.

## Actual behavior

<details>
<summary>$ rvm install ruby-2.6.3</summary>

```
Searching for binary rubies, this might take some time.                 
No binary rubies available for: termux/4.9.241-perf-gf1e771d-ab3841f6fd23/aarch64/ruby-2.6.3.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for termux.                                       
Installing requirements for termux.                                     
Installing required packages: bash, curl, patch, bzip2, ca-certificates, gawk, clang, coreutils, curl, gawk, git, gnupg, gpgv, libc++, libclang, 
libclang-dev, libllvm, libxml2, make, ncurses, ncurses-ui-libs, openssl, openssl-dev, openssl-tool, readline, sqlite, tar, zlib, zlib-dev - pleas
e wait                              
Error running 'requirements_termux_libs_install bash curl patch bzip2 ca-certificates gawk clang coreutils curl gawk git gnupg gpgv libc++ libcla
ng libclang-dev libllvm libxml2 make ncurses ncurses-ui-libs openssl openssl-dev openssl-tool readline sqlite tar zlib zlib-dev',
please read /data/data/com.termux/files/home/.rvm/log/1605352970_ruby-2.6.3/package_install_bash_curl_patch_bzip2_ca-certificates_gawk_clang_core
utils_curl_gawk_git_gnupg_gpgv_libc++_libclang_libclang-dev_libllvm_libxml2_make_ncurses_ncurses-ui-libs_openssl_open.log
Requirements installation failed with status: 100.
```
</details>

## Fixing it

Here's what I modified to get it somewhat working on my phone:

**NOTE**: This isn't perfect yet - I don't know what would be the right replacement for:
-  `libncurses5-dev`. `ncurses` perhaps? 
- `libc6-dev` :shrug: 

<details>
<summary>$HOME/.rvm/scripts/functions/requirements/termux</summary>

```bash
#!/usr/bin/env bash

requirements_termux_lib_installed()
{
  pkg-query -s "$1" > /dev/null 2>&1 || return $?
}

requirements_termux_libs_install()
{
  pkg install "$@" || return $?
}

requirements_termux_libs_remove()
{
  pkg --yes remove "$@" || return $?
}

requirements_termux_define_base()
{
  requirements_check "$@" \
    autoconf automake bison ca-certificates curl libc6-dev libffi gdbm libncurses5-dev \
    libsqlite libtool libyaml make openssl patch pkg-config sqlite3 zlib1g

  requirements_${_system_name_lowercase}_define_libgmp
  requirements_${_system_name_lowercase}_define_libreadline
}

requirements_termux_define()
{
  case "$1" in
    (rvm)
      requirements_check bash curl patch bzip2 ca-certificates gawk
      ;;

    (*)
      requirements_check clang coreutils curl gawk git gnupg gpgv \
                         libc++ clang llvm libxml2 make ncurses ncurses-ui-libs \
                         openssl openssl-tool readline sqlite tar zlib
      ;;
  esac
}

```
</details>

## Environment info

<details>
<summary>$ rvm info</summary>

```
system:

  system:
    uname:        "Linux localhost 4.9.241-perf-gf1e771d-ab3841f6fd23 #1 SMP PREEMPT Fri Nov 13 04:11:02 UTC 2020 aarch64 Android"
    name:         "Termux"
    version:      "4.9.241-perf-gf1e771d-ab3841f6fd23"
    architecture: "aarch64"
    bash:         "/data/data/com.termux/files/usr/bin/bash => GNU bash, version 5.0.18(1)-release (aarch64-unknown-linux-android)"
    zsh:          "/data/data/com.termux/files/usr/bin/zsh => zsh 5.8 (aarch64-unknown-linux-android)"
    remote_path:  "termux/4.9.241-perf-gf1e771d-ab3841f6fd23/aarch64"

  rvm:
    version:      "1.29.10-next (master)"
    updated:      "35 minutes 30 seconds ago"
    path:         "/data/data/com.termux/files/home/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  homes:
    gem:          "not set"
    ruby:         "not set"

  binaries:
    ruby:         "/data/data/com.termux/files/usr/bin/ruby"
    irb:          "/data/data/com.termux/files/usr/bin/irb"
    gem:          "/data/data/com.termux/files/usr/bin/gem"
    rake:         "/data/data/com.termux/files/usr/bin/rake"

  environment:
    PATH:         "/data/data/com.termux/files/home/bin:/data/data/com.termux/files/home/.local/bin:/data/data/com.termux/files/home/.local/share/cargo/bin:/data/data/com.termux/files/home/.local/share/go/bin:/data/data/com.termux/files/home/.local/share/zinit/plugins/pyenv/shims:/data/data/com.termux/files/home/.local/share/zinit/plugins/pschmitt---pkp:/data/data/com.termux/files/home/.local/share/zinit/plugins/pschmitt---tesmart.sh:/data/data/com.termux/files/home/.local/share/zinit/plugins/vmware-tanzu---velero:/data/data/com.termux/files/home/.local/share/zinit/plugins/derailed---k9s:/data/data/com.termux/files/home/.local/share/zinit/plugins/alexellis---k3sup:/data/data/com.termux/files/home/.local/share/zinit/snippets/kubectl:/data/data/com.termux/files/home/.local/share/zinit/plugins/mptre---yank:/data/data/com.termux/files/home/.local/share/zinit/plugins/greymd---tmux-xpanes:/data/data/com.termux/files/home/.local/share/zinit/plugins/pschmitt---tmux-slay:/data/data/com.termux/files/home/.local/share/zinit/plugins/hypriot---flash:/data/data/com.termux/files/home/.local/share/zinit/plugins/hetznercloud---cli:/data/data/com.termux/files/home/.local/share/zinit/plugins/hashicorp---vault:/data/data/com.termux/files/home/.local/share/zinit/plugins/hashicorp---terraform:/data/data/com.termux/files/home/.local/share/zinit/plugins/sharkdp---fd:/data/data/com.termux/files/home/.local/share/zinit/plugins/direnv---direnv:/data/data/com.termux/files/home/.local/share/zinit/plugins/Homebrew---brew/bin:/data/data/com.termux/files/home/.local/share/zinit/plugins/github---hub:/data/data/com.termux/files/home/.local/share/zinit/plugins/zdharma---zsh-diff-so-fancy/bin:/data/data/com.termux/files/home/.local/share/zinit/plugins/dylanaraps---fff:/data/data/com.termux/files/home/.local/share/zinit/polaris/sbin:/data/data/com.termux/files/home/.local/share/zinit/polaris/bin:/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets:/system/bin:/data/data/com.termux/files/home/.local/share/zinit/plugins/johanhaleby---kubetail:/data/data/com.termux/files/home/.rvm/bin"
    GEM_HOME:     ""
    GEM_PATH:     ""
    MY_RUBY_HOME: ""
    IRBRC:        ""
    RUBYOPT:      ""
    gemset:       ""
```
</details>

### PR DESCRIPTION
**Pull request by BrianHawley**
Changes proposed in this pull request:
* Remove unnecessary and unsupported dependencies.
* No getent, so use echo $SHELL instead.
* Add Windows:Mingw and Linux:Termux support to __rvm_get_user_shell
  duplicate declaration in warning_zsh too.

Fixes #5003, #5048, #5057

### CODE REVIEW

**Comment by BrianHawley** [comment]
I verified this by installing rvm from my branch in Termux using this command:
```sh
\curl -sSL https://get.rvm.io | bash -s source github.com/BrianHawley/rvm branch issue_5003
```
Then I ran `rvm requirements` and `rvm install ruby-3` and they both worked; Ruby 3.0.2 compiled and installed. I don't know what other Ruby versions work, or what platform-specific bugs exist for specific versions.

**Comment by BrianHawley** [comment]
@pkuczynski and @pedrofurtado this PR was requested by you in the referenced issues.

**Comment by pkuczynski** [comment]
Great work! Thank you @BrianHawley!

**Comment by BrianHawley** [comment]
Just tried reinstalling from scratch, and it didn't work. Working through the issues now. Don't merge yet.

**Comment by pkuczynski** [comment]
Should we merge it in then, or wait?

**Comment by BrianHawley** [comment]
It should be safe to merge. It solves the issue of rvm install, and of regular ruby install (presumably of compatible versions).

The main problem is too many unnecessary packages referenced, but that doesn't block builds; it just makes builds slower. That kind of issue can be fixed in a later PR.

**Comment by pkuczynski** [comment]
> It should be safe to merge. It solves the issue of rvm install, and of regular ruby install (presumably of compatible versions).

Cool. I am merging this in.
 
> The main problem is too many unnecessary packages referenced, but that doesn't block builds; it just makes builds slower. That kind of issue can be fixed in a later PR.

Can you have a look at it maybe?

**Comment by BrianHawley** [comment]
> > The main problem is too many unnecessary packages referenced, but that doesn't block builds; it just makes builds slower. That kind of issue can be fixed in a later PR.
> 
> Can you have a look at it maybe?

That's my plan.

As it is, the built-in Termux ruby package installs faster (from binary, I think), but it's always updated to the latest Ruby version (like Homebrew), and there are no non-MRI packages. I'll see if I can get other rubies working.

**Pull request merged**
