### PR TITLE
JRuby 9.4.0.0

### PR DESCRIPTION
**Pull request by headius**
Adds JRuby 9.4.0.0.

### CODE REVIEW

**Comment by headius** [comment]
I can't tell what failed in those jobs but it does not seem related to JRuby.

**Comment by pkuczynski** [comment]
Could you also update `config/known`. I noticed that we forgot to update it for normal ruby too, so separate PR for this would be also welcomed!

**Comment by headius** [comment]
Looks like #5270 may be more complete? If so that one is just fine to merge.

**Comment by havenwood** [comment]
Congrats on JRuby 9.4.0.0 release!

Closing since #5270 was merged, as suggested.

**Pull request closed without merging**
