### PR TITLE
add ruby 2.4.0

### PR DESCRIPTION
**Pull request by vincentaubert**

### CODE REVIEW

**Comment by pkuczynski** [comment]
Missing 'config/db' update and entry in CHANGELOG

**Comment by ur5us** [comment]
@pkuczynski I don't think anything needs to be added to `config/db` but an entry to the CHANGELOG is missing indeed.

**Comment by pkuczynski** [comment]
There is a line listing latest MRI ruby. It now points to 2.3.3

**Comment by ur5us** [comment]
@pkuczynski Ah, I see, thanks for clarifying it.

**Comment by vincentaubert** [comment]
fixed

**Pull request merged**
