### PR TITLE
Updating checksums for CentOS 6 and 7

### PR DESCRIPTION
**Pull request by hammady**
Updated binary ruby checksums

### CODE REVIEW

**Comment by pkuczynski** [comment]
@hammady could you please fix the checksum files, so this PR includes only things which you changed, and not the things coming out from wrong sorting.

**Comment by pkuczynski** [comment]
Does this PR solve #4222?

**Comment by hammady** [comment]
@pkuczynski not yet, I will push another commit.

**Comment by hammady** [comment]
Closing as being fixed in #4233.

**Pull request closed without merging**
