### PR TITLE
Updates and fixes to switch to new JRuby binary URL.

### LINKED ISSUE #4223: New JRuby download URLs 9.1.14.0+
JRuby's download URLs are changing! We will soon stop hosting our release artifacts on S3 due, and instead would prefer that all downloads come from Maven servers.

To that end, we have started pushing additional checksums with our "jruby-dist" artifact so these download URLs can be considered canonical.

This change affects JRuby 9.1.14.0 and higher. Previous releases will remain on S3 until it goes away.

There are three changes needed in RVM:

The base URL for the binary release tarball changes to `https://repo1.maven.org/maven2/org/jruby/jruby-dist/<version>/jruby-dist-<version>-bin.tar.gz`

The base URL for the source release tarball changes to `https://repo1.maven.org/maven2/org/jruby/jruby-dist/<version>/jruby-dist-<version>-src.tar.gz`

And as you see here, the structure of the tarball file changed from `jruby-bin-<version>.tar.gz` to `jruby-dist-<version>-bin.tar.gz` due to Maven requirements.

We do not know when our S3 will go away, so the sooner you can update how you fetch these files, the better!

### PR DESCRIPTION
**Pull request by headius**
Changes proposed in this pull request:
* Switch download URL to Maven address.
* Fix structure of tarball filename.
* Allow "HTTP/2 200" format in curl results.

Fixes #4223.

### CODE REVIEW

**Comment by headius** [comment]
Unsure if I did changelog right...let me know if changes are needed.

**Comment by headius** [comment]
I was also not sure if these changes are correct. The downloaded JRuby tarball in archives seems to go to an unusual filename like `bin-jruby-9.2.0.0.tar.gz` for some reason.

**Comment by headius** [comment]
cc @pkuczynski @mpapis for review and assistance :-)

**Comment by mpapis** [comment]
Just checked, works as expected :)

The file name locally is to unify, not all distributions have different name for source and binary, we used the `bin-` prefix to distinguish that - I guess each ruby should have it's own file name builder to allow using original name when possible ... but it would be some refactoring that we are trying to prevent if it's working - unless @pkuczynski got some time to play with it.

**Comment by headius** [comment]
@mpapis Thank you!

**Comment by ioquatix** [comment]
Thanks everyone for sorting this out so quickly!

**Pull request merged**
