### PR TITLE
Fix Rubinius build on macOS with Homebrew

### LINKED ISSUE #4327: Rubinius (rbx-3.100) fails on MacOS 10.13.3 (High Sierra)
## Description

`rvm install rbx-3.100` fails on High Sierra (compile error)

## Steps to reproduce

 1. `rvm get master`
 2. `rvm install rbx-3.100`

## Expected behavior

A successful installation.

## Actual behavior

* [configure.log](https://gist.github.com/CpuID/74b055eb9703336216bc83c91f2e96d1)
* [rake.log](https://gist.github.com/CpuID/8a493f8ab274f87187995062d773f8c6)

## Environment info

```
[nathan@NS-MB-Pro ~]$ rvm info

ruby-2.2.0:

  system:
    uname:        "Darwin NS-MB-Pro.home.nightsys.net 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64"
    name:         "OSX"
    version:      "10.13"
    architecture: "x86_64"
    bash:         "/usr/local/bin/bash => GNU bash, version 4.4.12(1)-release (x86_64-apple-darwin17.0.0)"
    zsh:          "/bin/zsh => zsh 5.3 (x86_64-apple-darwin17.0)"
    remote_path:  "osx/10.13/x86_64"

  rvm:
    version:      "1.29.3 (master)"
    updated:      "11 minutes 14 seconds ago"
    path:         "/Users/nathan/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "ruby"
    version:      "2.2.0p0"
    date:         "2014-12-25"
    platform:     "x86_64-darwin14"
    patchlevel:   "2014-12-25 revision 49005"
    full_version: "ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]"

  homes:
    gem:          "/Users/nathan/.rvm/gems/ruby-2.2.0"
    ruby:         "/Users/nathan/.rvm/rubies/ruby-2.2.0"

  binaries:
    ruby:         "/Users/nathan/.rvm/rubies/ruby-2.2.0/bin/ruby"
    irb:          "/Users/nathan/.rvm/rubies/ruby-2.2.0/bin/irb"
    gem:          "/Users/nathan/.rvm/rubies/ruby-2.2.0/bin/gem"
    rake:         "/Users/nathan/.rvm/gems/ruby-2.2.0/bin/rake"

  environment:
    PATH:         "/usr/local/sbin:/Users/nathan/.rvm/gems/ruby-2.2.0/bin:/Users/nathan/.rvm/gems/ruby-2.2.0@global/bin:/Users/nathan/.rvm/rubies/ruby-2.2.0/bin:/Users/nathan/vault:/Users/nathan/terraform:/Users/nathan/packer:/Users/nathan/git/stackexchange-blackbox/bin:/Users/nathan/go/bin:/Library/Frameworks/GDAL.framework/Programs:/Users/nathan/perl5/bin:/Users/nathan/.nvm/versions/node/v6.1.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/nathan/.rvm/bin:/Users/nathan/git/tedconf/infrastructure/bin:/Users/nathan/.rvm/bin:/usr/local/cuda/bin"
    GEM_HOME:     "/Users/nathan/.rvm/gems/ruby-2.2.0"
    GEM_PATH:     "/Users/nathan/.rvm/gems/ruby-2.2.0:/Users/nathan/.rvm/gems/ruby-2.2.0@global"
    MY_RUBY_HOME: "/Users/nathan/.rvm/rubies/ruby-2.2.0"
    IRBRC:        "/Users/nathan/.rvm/rubies/ruby-2.2.0/.irbrc"
    RUBYOPT:      ""
    gemset:       ""
```

### PR DESCRIPTION
**Pull request by pkuczynski**
Based on https://book.rubinius.com/manuscript/getting_rubinius.html

Fixes #4327

### CODE REVIEW

**Comment by saizai** [comment]
Should the llvm / clang parts be added to non-homebrew too? I've noticed this being needed in macports. Also, the llvm version required has changed in different versions of rbx, but I don't recall which.

**Comment by saizai** [comment]
(If I'm right about that, `port select llvm [version]` may be the right approach, putting it back when done.)

**Comment by saizai** [comment]
You've already gotten a few from me. Only so many spoons to spare. ;-)

**Comment by CpuID** [comment]
thx :)

**Pull request merged**
