### PR TITLE
Add TruffleRuby 1.0.0-rc12

### PR DESCRIPTION
**Pull request by eregon**
cc @pkuczynski  @havenwood

BTW, could we merge https://github.com/rvm/rvm/pull/4576 too?

### CODE REVIEW

**Comment by eregon** [comment]
Also, is it useful/necessary to update the ChangeLog for new TruffleRuby releases? It's one manual step that cannot be easily automated, causes a second CI run, and doesn't seem so useful.

**Comment by havenwood** [comment]
> Also, is it useful/necessary to update the ChangeLog for new TruffleRuby releases? It's one manual step that cannot be easily automated, causes a second CI run, and doesn't seem so useful.

We used to do the release changelog notes all at once, at the time of release. I think @pkuczynski switched to asking for notes per PR so missing changelog updates wouldn't always be blocking release.

One option might be to use a script to generate the changelog at release time from merged PRs. That might be fairly difficult to do unless we change the changelog format. Or we could stop doing release changelogs.

**Comment by havenwood** [comment]
@pkuczynski How do you feel about the release changelog? Worth attempting to generate it at release time, deprecate it, or keep it as as?

**Comment by pkuczynski** [comment]
Format-wise I don't mind having every version as a separate entry. But it's better to have changelog modified with every PR. Otherwise users for `master` would not know what changed. And creating changelog after weeks of development is painful.

**Comment by pkuczynski** [comment]
I see your point for automation and I think we can live without the PR number :)

**Comment by eregon** [comment]
@pkuczynski  Great, I'll make the script add a line in the ChangeLog then :)

**Pull request merged**
