### PR TITLE
Add TruffleRuby 24.0.0

### PR DESCRIPTION
**Pull request by eregon**
https://github.com/oracle/truffleruby/releases/tag/graal-24.0.0

### CODE REVIEW

**Review by nirvdrum — APPROVED** [review]
The changes look good to me.

**Comment by eregon** [comment]
@pkuczynski It seems I cannot merge this PR even with an approval, even though both @nirvdrum and I have write access. I guess there are some special branch protection rules for `master` where only specific people can merge?
Screenshot from 2024-03-19 17-16-19
(the link is [this](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches))

In any case, could you review & merge this?

**Comment by pkuczynski** [comment]
That's only because build failed on macOS

**Review by pkuczynski — APPROVED** [review]

**Comment by eregon** [comment]
Ah right, probably it makes sense to mark `CI / tests (macos-latest)` as not required since it's been failing for a while.
I'm looking at it in https://github.com/rvm/rvm/issues/4579 / #5387

**Pull request merged**
