### PR TITLE
Add JRuby 1.7.21 as the default JRuby

### PR DESCRIPTION
**Pull request by donv**

### CODE REVIEW

**Comment by holstvoogd** [comment]
:+1: 
btw, the travis failure is just a timeout..

**Comment by havenwood** [comment]
I think this just needs checksums, [here](https://github.com/rvm/rvm/blob/master/config/md5) and [here](https://github.com/rvm/rvm/blob/master/config/sha512).

**Comment by donv** [comment]
OK, how do I create the checksums?

**Comment by havenwood** [comment]
Checking the sums locally with `md5` and `shasum -a 512` I'm seeing:
```
https://s3.amazonaws.com/jruby.org/downloads/1.7.21/jruby-bin-1.7.21.tar.gz=bc91594072032023d146f330764d3274
```
and
```
https://s3.amazonaws.com/jruby.org/downloads/1.7.21/jruby-bin-1.7.21.tar.gz=111883df12a60d06e9924d33057ba72094fcffd44f7e3954d6c6d2190f8e6442804e739cc525a9e75159251a8dc1cc487570792b1b4f5773f4d0082f0eb360d0
```

The JRuby downloads page does have the md5 and sha1 but not the sha512. So depending on your system either `sha512sum`, `sha512 -r` or `shasum -a 512` then the archive.

**Comment by havenwood** [comment]
P.S., another place to confirm checksums is [ruby-version](https://github.com/postmodern/ruby-versions/tree/master/jruby), which is a common repository for Ruby version metadata.

**Comment by donv** [comment]
Hi @havenwood !

i added the checksums.  Hopefully ready to merge now.

This is a common task that could be documented for easy contribution.  Should I add a CHORES.md doc linked from CONTRIBUTING.md ?

**Comment by donv** [comment]
@mpapis anything more I need to do to get this merged?

**Comment by havenwood** [comment]
@donv Thanks! Sorry for the delay, was trying to get TravisCI to stop timing-out but it's not related to your pull request so merged. :shipit: 

I think it's a great idea to have a section that details how to bump versions!

**Comment by donv** [comment]
Thanks!

**Pull request merged**
