### PR TITLE
Add support for JRuby 9.1.14.0

### PR DESCRIPTION
**Pull request by koic**
## Summary

JRuby 9.1.14.0 has been released.
http://jruby.org/2017/11/08/jruby-9-1-14-0.html

## Other Information

JRuby 9.1.14.0+ download URL has changed.
https://github.com/rvm/rvm/issues/4223

### CODE REVIEW

**Comment by koic** [comment]
This PR can not be merged as it is.
It seems necessary to verify and change the URLs of JRuby 9.1.13 or lower.

**Comment by HarlemSquirrel** [comment]
It does seem to be working.

```sh
➤  for i in {1..14}; do
for> curl --head -s "https://repo1.maven.org/maven2/org/jruby/jruby-dist/9.1.$i.0/jruby-dist-9.1.$i.0-bin.tar.gz" | grep MD5
for> done
X-Checksum-MD5: 8356334270df07a214590d00a986837b
X-Checksum-MD5: 749bb917dde9666e365e12bbe776a5c2
X-Checksum-MD5: 91c246cd623702032e88283565da5480
X-Checksum-MD5: 5b80b78c09bf0cd4dcbcb9e1fe3e8b73
X-Checksum-MD5: e9b2cc44757db4cfbe7da79601d0169a
X-Checksum-MD5: 4092a89b01b55d1fb5498113f97ab0ca
X-Checksum-MD5: b120c3eaeef7ff2aed3a57701e414e78
X-Checksum-MD5: 0fdee002c56ec91dff1efffce205265c
X-Checksum-MD5: 170efc34297d7ac2a56bb1163e96b363
X-Checksum-MD5: b75e0d1a200e8f790d8bbc84f91e3002
X-Checksum-MD5: 0502a14141da25a460ce197720bab4c3
X-Checksum-MD5: 74bd7ae08c159fc62cb6f64845a868cc
X-Checksum-MD5: 6c642c8a2653a585779f453d8c843fd7
X-Checksum-MD5: a7e0ecd529690025d327c45744f60fa4
```

**Comment by HarlemSquirrel** [comment]
And the s3 bucket seems to no longer work.

```sh
➤  for i in {1..14}; do                                                                                                               1 ↵
curl --head -s "https://s3.amazonaws.com/jruby.org/downloads/9.1.$i.0/jruby-dist-9.1.$i.0-bin.tar.gz" | grep HTTP
done
HTTP/1.1 404 Not Found
HTTP/1.1 404 Not Found
HTTP/1.1 404 Not Found
HTTP/1.1 404 Not Found
HTTP/1.1 404 Not Found
HTTP/1.1 404 Not Found
HTTP/1.1 404 Not Found
HTTP/1.1 404 Not Found
HTTP/1.1 404 Not Found
HTTP/1.1 404 Not Found
HTTP/1.1 404 Not Found
HTTP/1.1 404 Not Found
HTTP/1.1 404 Not Found
HTTP/1.1 404 Not Found
```

**Comment by koic** [comment]
Even in the old JRuby download URL seems to be able to download JRuby 9.1.14.0.
https://s3.amazonaws.com/jruby.org/downloads/9.1.14.0/jruby-bin-9.1.14.0.tar.gz

In this PR, RVM installs JRuby using the old URL.

**Comment by pkuczynski** [comment]
Indeed! I will merge this in then and work on the Maven implementation (#4223) in the meantime...

**Comment by koic** [comment]
Thank you for working on essential implementation.

**Pull request merged**
