### PR TITLE
Fixes RVM package fails to configure on fresh Ubuntu 18.04 server install

### PR DESCRIPTION
**Pull request by pkuczynski**
Reverts #4612 and reopens #3410

Fixes rvm/ubuntu_rvm#37

### CODE REVIEW

**Comment by saydulk** [comment]
i did try https://github.com/rvm/ubuntu_rvm/issues/37 and others closed issues using ubuntu 18.04 LTS for this problem but still not able to work. IS this bug was fixed?  

Screenshot from 2019-10-19 02-08-40

**Comment by raelgc** [comment]
@saydulk Why are you logged as root to install rvm? Anyway, try remove this install and then try the [Ubuntu dedicated package](https://github.com/rvm/ubuntu_rvm).

**Comment by saydulk** [comment]
This https://github.com/rvm/ubuntu_rvm not worked 1st time setup. Btw i have solve the problem running: $ source /usr/share/rvm/scripts/rvm

**Comment by raelgc** [comment]
@saydulk I'm glad you solved your problem. But remember that you have to logout or restart to get `rvm` working after the Ubuntu install.

**Pull request merged**
