### PR TITLE
Rails express patch for Fiber.new{ }.resume for Ruby 3.3

### PR DESCRIPTION
**Pull request by skaes**
This will be included in ruby 3.3.1.

See https://bugs.ruby-lang.org/issues/20085

### CODE REVIEW

**Comment by skaes** [comment]
@pkuczynski not sure what to add to the CHANGELOG

**Review by pkuczynski — APPROVED** [review]

**Comment by pkuczynski** [comment]
This has been already added to master, as it seems so I am just closing it?

**Comment by skaes** [comment]
I'm confused. Looks like I might have forgotten to push the actual change.

**Comment by pkuczynski** [comment]
There was a patch added, but when I merged master it dissapeared. Maybe you also added it via another PR?

**Comment by skaes** [comment]
The file is in the source tree. So all is fine.

**Pull request closed without merging**
