### PR TITLE
Limit s3 lookup of rbx to correct versions (fixes #4311)

### LINKED ISSUE #4311: rvm version source lookup fails for rbx-3.99
From rvm source:
```
rbx_repo_url=https://github.com/rubinius/rubinius.git
rbx_url=https://s3.amazonaws.com/asset.rubini.us
rbx_url_2.0_and_newer=https://rubinius-releases-rubinius-com.s3.amazonaws.com
rbx_version=3.99
```

tl;dr if you try to `rvm install rbx-3.99`, it fails because it goes for the s3 based lookup. It should go for the github version. It works for `rvm install rbx`, which seems to avoid this version check.

The s3 version is *only* valid for the following versions (based on looking at the s3 right now), so "`rbx_url_2.0_and_newer`" is a misnomer:

```
rubinius-0.12-20091006
rubinius-0.13.0
rubinius-0.13.0-20091113
rubinius-1.0.0
rubinius-1.0.0-10.5
rubinius-1.0.0-10.6
rubinius-1.0.0-20100514
rubinius-1.0.0-rc1-20091125
rubinius-1.0.0-rc2-20100104
rubinius-1.0.0-rc2.10.5
rubinius-1.0.0-rc2.10.6
rubinius-1.0.0-rc3-10.5
rubinius-1.0.0-rc3-10.6
rubinius-1.0.0-rc3-20100216
rubinius-1.0.0-rc4-10.5
rubinius-1.0.0-rc4-10.6
rubinius-1.0.0-rc4-20100331
rubinius-1.0.0-rc5-20100510
rubinius-1.0.1
rubinius-1.0.1-10.5
rubinius-1.0.1-10.6
rubinius-1.0.1-20100603
rubinius-1.1.0
rubinius-1.1.0-10.5
rubinius-1.1.0-10.6
rubinius-1.1.0-20100923
rubinius-1.1.1
rubinius-1.1.1-10.5
rubinius-1.1.1-10.6
rubinius-1.1.1-20101116
rubinius-1.2.0
rubinius-1.2.0-10.5
rubinius-1.2.0-10.6
rubinius-1.2.0-20101221
rubinius-1.2.1
rubinius-1.2.1-10.5
rubinius-1.2.1-10.6
rubinius-1.2.1-20110215
rubinius-1.2.2
rubinius-1.2.2-10.5
rubinius-1.2.2-10.6
rubinius-1.2.2-20110222
rubinius-1.2.3
rubinius-1.2.3-10.5
rubinius-1.2.3-10.6
rubinius-1.2.3-20110315
rubinius-1.2.4
rubinius-1.2.4-10.6
rubinius-1.2.4-20110705
rubinius-2.0.0.n199-20130718
rubinius-2.0.0.rc1-20130123
rubinius-2.0.0dev-20111019
rubinius-2.0.0dev-20111025
rubinius-2.0.0dev-20111129
rubinius-2.0.0dev-20111213
rubinius-2.0.0dev-20120112
rubinius-2.0.0dev-20120115
rubinius-2.0.0dev-20120123
rubinius-2.0.0dev-20120410
rubinius-2.0.0dev-20120427
rubinius-2.0.0dev-20120502
rubinius-2.0.0dev-20120615
rubinius-2.0.0dev-20120627
rubinius-2.0.0dev-20120723
rubinius-2.0.0dev-20120725
rubinius-2.0.0dev-20120727-x86_64-unknown-linux-gnu
rubinius-2.0.0dev-20120919
rubinius-2.0.0dev-20121003
rubinius-2.0.0dev-20121024
rubinius-2.0.0dev-20121029
```

Error symptoms:
```
$ rvm list

rvm rubies

=> ruby-2.5.0 [ x86_64 ]

# => - current
# =* - current && default
#  * - default

$ rvm fetch rbx-3.99
rbx-3.99 - #downloading rubinius-3.99, this may take a while depending on your connection...
-=#=-  #     #        #
curl: (22) The requested URL returned error: 404 Not Found
The requested url does not exist(22): 'https://s3.amazonaws.com/releases.rubini.us/rubinius-3.99.tar.bz2'
Checking fallback: ftp://s3.amazonaws.com/releases.rubini.us/rubinius-3.99.tar.bz2
Checking fallback: https://www.mirrorservice.org/sites/s3.amazonaws.com/releases.rubini.us/rubinius-3.99.tar.bz2
No fallback URL could be found, try increasing timeout with:

    echo "export rvm_max_time_flag=20" >> ~/.rvmrc

$ CC=clang CXX=clang++ rvm install rbx-3.99 --clang
Checking requirements for osx_port.
Certificates bundle '/opt/local/etc/openssl/cert.pem' is already up to date.
Requirements installation successful.
Warning: found user selected compiler 'clang', this will suppress RVM auto detection mechanisms.
Regenerating ruby-2.5.0 wrappers........
Saved wrapper: /Users/saizai/.rvm/bin/textmate_ruby
Saved wrapper: /Users/saizai/.rvm/bin/textmate_gem
Saved wrapper: /Users/saizai/.rvm/bin/textmate_irb
Saved wrapper: /Users/saizai/.rvm/bin/textmate_ri
Saved wrapper: /Users/saizai/.rvm/bin/textmate_rdoc
Saved wrapper: /Users/saizai/.rvm/bin/textmate_rake
Saved wrapper: /Users/saizai/.rvm/bin/textmate_erb
Saved wrapper: /Users/saizai/.rvm/bin/textmate_testrb
ruby-2.5.0@rubinius - #regenerating binstubs...........
Downloading source from https://s3.amazonaws.com/releases.rubini.us/rubinius-3.99.tar.bz2..
Error running 'svn checkout -q https://s3.amazonaws.com/releases.rubini.us/rubinius-3.99.tar.bz2 /Users/saizai/.rvm/repos/rbx',
please read /Users/saizai/.rvm/log/1519219684_rbx-3.99/svn.checkout.log
There has been an error while trying to fetch / update the source.
Halting the installation.

$ cat /Users/saizai/.rvm/log/1519219684_rbx-3.99/svn.checkout.log
[2018-02-21 13:28:04] svn
current path: [redacted]
command(5): svn checkout -q https://s3.amazonaws.com/releases.rubini.us/rubinius-3.99.tar.bz2 /Users/saizai/.rvm/repos/rbx
svn: E125001: Couldn't determine absolute path of '.'
svn: E000002: No such file or directory

$ CC=clang CXX=clang++ rvm install rbx --clang
Checking requirements for osx_port.
Certificates bundle '/opt/local/etc/openssl/cert.pem' is already up to date.
Requirements installation successful.
Warning: found user selected compiler 'clang', this will suppress RVM auto detection mechanisms.
Regenerating ruby-2.5.0 wrappers........
ruby-2.5.0@rubinius - #regenerating binstubs...........
Cloning from https://github.com/rubinius/rubinius.git, this may take a while depending on your connection.
[snip]
```

### PR DESCRIPTION
**Pull request by saizai**
Fixes #4311.

Changes proposed in this pull request: 
* add whitelist of s3-hosted versions of rbx
* check against whitelist, use git for all other rbx versions

### CODE REVIEW

**Comment by saizai** [comment]
@pkuczynski, @mpapis ?

**Comment by mpapis** [comment]
is it possible the s3 lookup got paged and the results were cut short, I can see 3.99 on the list for s3.

**Comment by saizai** [comment]
Possibly. Ask @brixen?

**Comment by saizai** [comment]
I can't work on this right now; I have legal issues to deal with.

**Comment by saizai** [comment]
FWIW, general case fix would be to fall back to git if s3 lookup fails. (Which rvm doesn't currently do.)

**Comment by pkuczynski** [comment]
https://rubinius-releases-rubinius-com.s3.amazonaws.com contains newer versions of rbx

**Comment by saizai** [comment]
@mpapis reopen per above?

**Pull request closed without merging**
