### PR TITLE
Add float_warnings patchsets for ruby 2.1.[67] and 2.2.[0123]

### PR DESCRIPTION
**Pull request by knugie**

### CODE REVIEW

**Comment by sikachu** [comment]
Do you mind update your commit message to be more descriptive on what this patchset does and maybe a link to any issue that you have ran into that made you created this patch?

/cc @havenwood wdyt about this patch?

**Comment by knugie** [comment]
Hi sikachu, just like previous PRs (https://github.com/rvm/rvm/pulls?q=is%3Apr+is%3Aclosed+author%3Aknugie) these patches are used to warn you whenever you want to instantiate a BigDecimal with an instance of float, fmi see https://slides.com/wolfgangteuber/saving-money-with-ruby/fullscreen# and https://github.com/knugie/rvm-patchsets#rvm-patchsets-for-mri-ruby
This particular PR provides this patch for the latest 6 Ruby versions.

**Comment by mpapis** [comment]
we already got 30 patches like this, merging

**Comment by knugie** [comment]
:+1: Thanks Michal

**Pull request merged**
