### PR TITLE
Add TruffleRuby 19.2.0

### PR DESCRIPTION
**Pull request by eregon**
Add TruffleRuby 19.2.0

### CODE REVIEW

**Comment by eregon** [comment]
(I made a PR to check if the CI passes)

**Comment by pkuczynski** [comment]
Build fails, so I am not merging just yet...

**Comment by eregon** [comment]
I'd say let's merge since the failure is only on macOS and seems completely unrelated. Is it a known issue though?

**Comment by eregon** [comment]
There seems to be the same failure on master: https://travis-ci.org/rvm/rvm/builds/574280336
@mpapis Maybe we should just `allow_failures` that job until it's fixed?

**Pull request merged**
