### PR TITLE
Add support for JRuby 9.2.0.0

### PR DESCRIPTION
**Pull request by HarlemSquirrel**

### CODE REVIEW

**Comment by havenwood** [comment]
I think the `jruby[-9.1.17.0]` [here](https://github.com/rvm/rvm/pull/4390/files#diff-278dcece756e75611dd08c63d01cc4b2R21) should be changed to `jruby-9.1[.17.0]` or omitted.

**Comment by HarlemSquirrel** [comment]
@havenwood Makes sense to me. I've updated my branch.

**Comment by havenwood** [comment]
I think [this one](https://github.com/rvm/rvm/pull/4390/files#diff-278dcece756e75611dd08c63d01cc4b2R22) should stay `jruby[-9.2.0.0]`, since it's what you get if you just `rvm install jruby`.

**Comment by HarlemSquirrel** [comment]
@havenwood OK, updated.

**Pull request merged**
