### PR TITLE
Fix unknown command wrappers

### LINKED ISSUE #5020: Error when generating default wrappers in 'rvm install 3.0.0'
Hey everyone! 👋 

Operating system: CentOS 8
Ruby version: 3.0.0
RVM version: HEAD, 1.29.10-next (master)

@pkuczynski I tried to install ruby 3.0.0 with rvm codebase in branch master (because version 1.29.11 is not released yet).

After executed `rvm get head`, I executed `rvm install 3.0.0` and I got this output:

```bash
[root@localhost vagrant]# rvm install 3.0.0
Searching for binary rubies, this might take some time.
No binary rubies available for: centos/8/x86_64/ruby-3.0.0.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for centos.
Requirements installation successful.
Installing Ruby from source to: /usr/local/rvm/rubies/ruby-3.0.0, this may take a while depending on your cpu(s)...
ruby-3.0.0 - #downloading ruby-3.0.0, this may take a while depending on your connection...
ruby-3.0.0 - #extracting ruby-3.0.0 to /usr/local/rvm/src/ruby-3.0.0.....
ruby-3.0.0 - #configuring.........................................................................
ruby-3.0.0 - #post-configuration..
ruby-3.0.0 - #compiling....................................................................................|.......
ruby-3.0.0 - #installing.....................
ruby-3.0.0 - #making binaries executable...
Installed rubygems 3.2.3 is newer than 3.0.9 provided with installed ruby, skipping installation, use --force to force installation.
ruby-3.0.0 - #gemset created /usr/local/rvm/gems/ruby-3.0.0@global
ruby-3.0.0 - #importing gemset /usr/local/rvm/gemsets/global.gems..........................................|......................
ruby-3.0.0 - #generating global wrappers.......
ruby-3.0.0 - #gemset created /usr/local/rvm/gems/ruby-3.0.0
ruby-3.0.0 - #importing gemsetfile /usr/local/rvm/gemsets/default.gems evaluated to empty gem list
ruby-3.0.0 - #generating default wrappers........
Error running 'run_gem_wrappers regenerate',
please read /usr/local/rvm/log/1609002698_ruby-3.0.0/gemset.wrappers.default.log
ruby-3.0.0 - #adjusting #shebangs for (gem irb erb ri rdoc testrb rake).
Install of ruby-3.0.0 - #complete
Ruby was built without documentation, to build it run: rvm docs generate-ri
```

The content of log file `/usr/local/rvm/log/1609002698_ruby-3.0.0/gemset.wrappers.default.log` is:

```bash
[2020-12-26 14:15:01] run_gem_wrappers
run_gem_wrappers ()
{
    gem_install gem-wrappers > /dev/null && gem wrappers "$@" || return $?
}
current path: /usr/local/rvm/src/ruby-3.0.0
GEM_HOME=/usr/local/rvm/gems/ruby-3.0.0
GEM_PATH=/usr/local/rvm/gems/ruby-3.0.0:/usr/local/rvm/gems/ruby-3.0.0@global
PATH=/usr/local/rvm/gems/ruby-3.0.0/bin:/usr/local/rvm/gems/ruby-3.0.0@global/bin:/usr/local/rvm/rubies/ruby-3.0.0/bin:/usr/local/rvm/bin:/sbin:/bin:/usr/sbin:/usr/bin
command(2): run_gem_wrappers regenerate
++ gem_install gem-wrappers
++ typeset gem_name gem_version version_check
++ gem_version=
++ __rvm_parse_gems_args gem-wrappers
++ typeset gem=gem-wrappers
++ __rvm_string_match gem-wrappers '*.gem$'
++ typeset _string
++ _string=gem-wrappers
++ shift
++ ((  1  ))
++ case "${_string}" in
++ shift
++ ((  0  ))
++ return 1
++ gem_name=gem-wrappers
++ case "$gem" in
++ [[ -z '' ]]
++ __rvm_db gem_gem-wrappers_version gem_version
++ typeset value key variable
++ key=gem_gem-wrappers_version
++ variable=gem_version
++ value=
++ [[ -f /usr/local/rvm/user/db ]]
+++ __rvm_db_ /usr/local/rvm/user/db gem_gem-wrappers_version
+++ typeset __db __key __value
+++ __db=/usr/local/rvm/user/db
+++ __key=gem_gem-wrappers_version
+++ shift 2
+++ __value=
+++ case "${__value}" in
+++ __rvm_db_get /usr/local/rvm/user/db gem_gem-wrappers_version
+++ [[ -f /usr/local/rvm/user/db ]]
+++ __rvm_sed -n -e '\#^gem_gem-wrappers_version=# { s#^gem_gem-wrappers_version=##;; p; }' -e '/^$/d'
+++ sed -n -e '\#^gem_gem-wrappers_version=# { s#^gem_gem-wrappers_version=##;; p; }' -e '/^$/d'
++ value=
++ [[ -z '' ]]
++ [[ -f /usr/local/rvm/config/db ]]
+++ __rvm_db_ /usr/local/rvm/config/db gem_gem-wrappers_version
+++ typeset __db __key __value
+++ __db=/usr/local/rvm/config/db
+++ __key=gem_gem-wrappers_version
+++ shift 2
+++ __value=
+++ case "${__value}" in
+++ __rvm_db_get /usr/local/rvm/config/db gem_gem-wrappers_version
+++ [[ -f /usr/local/rvm/config/db ]]
+++ __rvm_sed -n -e '\#^gem_gem-wrappers_version=# { s#^gem_gem-wrappers_version=##;; p; }' -e '/^$/d'
+++ sed -n -e '\#^gem_gem-wrappers_version=# { s#^gem_gem-wrappers_version=##;; p; }' -e '/^$/d'
++ value='>=1.4.0'
++ [[ -n >=1.4.0 ]]
++ [[ -n gem_version ]]
++ eval 'gem_version='\''>=1.4.0'\'''
+++ gem_version='>=1.4.0'
++ true
++ ((  0 == 0  ))
++ is_gem_installed
++ typeset gem_spec
++ gem_spec='gem '\''gem-wrappers'\'''
++ [[ -n >=1.4.0 ]]
++ gem_spec+=', '\''>=1.4.0'\'''
++ version_check=1.4.0
++ __rvm_ls -ld /usr/local/rvm/gems/ruby-3.0.0/gems/gem-wrappers-1.4.0
++ /usr/local/rvm/rubies/ruby-3.0.0/bin/ruby -rrubygems -e 'gem '\''gem-wrappers'\'', '\''>=1.4.0'\'''
++ rvm_log 'gem gem-wrappers >=1.4.0 is already installed'
++ [[ '' == 1 ]]
++ printf %b 'gem gem-wrappers >=1.4.0 is already installed\n'
++ return 0
++ gem wrappers regenerate
ERROR:  While executing gem ... (Gem::CommandLineError)
    Unknown command wrappers
++ return 1
```

### PR DESCRIPTION
**Pull request by wintersolutions**
Rubygems plugin loading was changed in
rubygems >= 3.2 this leads to gem-wrappers
not being loaded in a new context.

This fix registers the gem-wrappers plugin before its
being used.

See https://github.com/rubygems/rubygems/pull/3108

Fixes #5020.

Changes proposed in this pull request:
* Run `gem pristine gem-wrappers --only-plugins` before running `gem wrappers regenerate` to avoid plugin loading issues with rubygems >= 3.2

Make sure that your pull request includes entry in the [CHANGELOG](CHANGELOG.md).

### CODE REVIEW

**Comment by pedrofurtado** [comment]
@pkuczynski @mpapis Happy to see this merged asap 🎉 🎉 

Thanks @wintersolutions ! 🤝

**Comment by pedrofurtado** [comment]
@pkuczynski @mpapis I've tested locally the branch, and it worked like a charm 🎉

**Review by pkuczynski — APPROVED** [review]
Thanks!

**Comment by pedrofurtado** [comment]
@pkuczynski When you have time, could you release a minor version of rvm for us? 🤝  We are waiting a official release with this hotfix to upgrade rvm in our production environments 👍 🏆

**Comment by wintersolutions** [comment]
Thanks!

**Comment by teeigeryuh** [comment]
I tried multiple clean installs of debian10, and I'm getting this after this change:
```
dan@cibo:~$ \curl -sSL https://get.rvm.io | bash -s -- --ignore-dotfiles
Turning on ignore dotfiles mode.
Downloading https://github.com/rvm/rvm/archive/master.tar.gz
/home/dan/.rvm/src/rvm/scripts/functions/installer: line 1420: syntax error near unexpected token `('
/home/dan/.rvm/src/rvm/scripts/functions/installer: line 1420: `            __rvm_with "${__gem_home##*/}" (gem pristine gem-wrappers --only-plugins || true) && gem wrappers regenerate'
Installing RVM to /home/dan/.rvm/
/home/dan/.rvm/src/rvm/scripts/functions/installer: line 26: update_gemsets_install_rvm: command not found
/home/dan/.rvm/src/rvm/scripts/functions/installer: line 26: configure_autolibs: command not found
/home/dan/.rvm/src/rvm/scripts/functions/installer: line 26: update_yaml_if_needed: command not found
/home/dan/.rvm/src/rvm/scripts/functions/installer: line 26: cleanup_tmp_files: command not found
/home/dan/.rvm/src/rvm/scripts/functions/installer: line 26: record_installation_time: command not found
/home/dan/.rvm/src/rvm/scripts/functions/installer: line 26: print_install_footer: command not found
/home/dan/.rvm/src/rvm/scripts/functions/installer: line 26: display_notes: command not found
```

**Comment by pedrofurtado** [comment]
@teeigeryuh Take a look on this PR that I've created. Thanks for feedback!: https://github.com/rvm/rvm/pull/5029

**Pull request merged**
