### PR TITLE
added railsexpress patches for ruby 3.2

### PR DESCRIPTION
**Pull request by skaes**
Can you please merge this after I have added the CHANGELOG entry which I can only do after having created the PR because only then I know the correct PR number?

Thx a lot.

### CODE REVIEW

**Comment by hurricup** [comment]
Sorry, but I have no idea what is this about. I'm not a maintainer here, just helping with new release updates. you should ask someone else.

**Comment by skaes** [comment]
@hurricup I just picked you because you were active today and it's xmas. Sorry about that.

**Comment by hurricup** [comment]
sorry couldn't help you :( merry xmas to you :D

**Comment by pkuczynski** [comment]
I can and I am around :)

**Review by pkuczynski — APPROVED** [review]

**Comment by skaes** [comment]
thx @pkuczynski and merry xmas to you all!

**Pull request merged**
