### PR TITLE
Update Truffleruby to 19.1.1

### PR DESCRIPTION
**Pull request by skunkworker**
Updated Truffleruby to 19.1.1.

Unfortunately it looks like new releases 19.1.1+ don't include `truffleruby` in the .tar.gz name anymore but are like `ruby-standalone-svm-linux-amd64-19.1.1.tar.gz`.

### CODE REVIEW

**Comment by pkuczynski** [comment]
@eregon?

**Comment by eregon** [comment]
There was no change for TruffleRuby in 19.1.1 vs 19.1.0, so I'd rather not add it to any Ruby manager.
Is there a particular reason you want to use 19.1.1 instead of 19.1.0?

You are right, the filename is incorrect, we'll fix it.

**Comment by pkuczynski** [comment]
I will close it for now, but you can continue discussing details here...

**Comment by ezzarghili** [comment]
The release artifacts names for the standalone versions were updated to follow the consistent name used before, sorry for the inconvenience.
```
truffleruby-19.1.1-macos-amd64.tar.gz
truffleruby-19.1.1-linux-amd64.tar.gz
```

**Pull request closed without merging**
