### PR TITLE
Add JRuby 9.3.13.0 and 9.4.5.0

### PR DESCRIPTION
**Pull request by headius**
Adds JRuby 9.3.13.0 and 9.4.5.0.

### CODE REVIEW

**Review by mathieujobin — APPROVED** [review]
not sure why CI is failing though...

**Comment by pkuczynski** [comment]
What about 9.3.12? Seems like we are missing it?

**Comment by pkuczynski** [comment]
> not sure why CI is failing though...

Probably openssl issue. It only fails on macOS.

**Comment by headius** [comment]
The 9.3.12.0 release got a bit messed up and we had to skip it.

**Pull request merged**
