### PR TITLE
Fix 2.7.8 checksums

### PR DESCRIPTION
**Pull request by VladRassokhin**
Fixes incorrect checksums added in #5336.

### CODE REVIEW

**Comment by pkuczynski** [comment]
@hurricup can you check please?

**Comment by hurricup** [comment]
Will be able in few days. Away currently.

**Review by hurricup — APPROVED** [review]
This was my mistake. I copy-pasted previous line from 2.7.7, changed version and updated sums.
But, i'm usually downloading and using gz instead of bz2.

So we have bz2 file with gz checksums:
```
3a9db8d9e79318f869417f2ebf3365907febc0d1428116eabf3253c51d8420f255782b32fa30a54802b9f5f4187fad80dab0611cc80436feec84db87b0456ec6  ruby-2.7.8.tar.bz2
f44dedf51fdb7441a7dba592d6a4a14d  ruby-2.7.8.tar.bz2
23195d29cec81f54061db14fbc9d0d75aca71ca4de35da3d5712eb08d71fbe27a3f0f2594b58692cf20225188334879e413ac078d10d7b635af0200d02f25ecb  ruby-2.7.8.tar.gz
b2d59ce994ae3d9715b15f842b2f9751  ruby-2.7.8.tar.gz
```

**Comment by pkuczynski** [comment]
Thank you @VladRassokhin

**Pull request merged**
