### PR TITLE
Add support for Ruby 2.6.1

### PR DESCRIPTION
**Pull request by AirWick219**
Ruby 2.6.1 has been released.
https://www.ruby-lang.org/en/news/2019/01/30/ruby-2-6-1-released/

Changes proposed in this pull request:
* Add support for Ruby 2.6.1

### CODE REVIEW

**Comment by pcarn** [comment]
Change config/db file line 82

**Comment by pcarn** [comment]
@pkuczynski ready for 2.6.1

**Comment by PikachuEXE** [comment]
I can install 2.6.1 without this PR
What's the magic behind it?

**Comment by pcarn** [comment]
> I can install 2.6.1 without this PR
> What's the magic behind it?

If you specify 2.6.1, it will install it. 
If you use `ruby-2.6`, it will automatically take patch versions. It will install the newest version of ruby that RVM knows about. 
This PR updates that so that 2.6.1 is recognized.

**Comment by havenwood** [comment]
Thank you for the PR!

**Pull request merged**
